### ISSUE TITLE
Rename theme.less to index.less

### ISSUE THREAD

**Issue by booploops** [deerwithacurl/CiderMaterialYou#2]
Love the theme!
I noticed the main theme file is named theme.less for Cider to read it properly the entry less file needs to be called index.less otherwise it cannot read the theme correctly.
![image](https://user-images.githubusercontent.com/49113086/154197942-81ddaa78-0986-46f8-844f-1891b9e9248b.png)

**Comment by deerwithacurl** [comment]
fixed with merged pull request, thank you!
