### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by dnestico** [deerwithacurl/CiderMaterialYou#4]
I go and hit the install button and it just fails. 

I just downloaded cider so I am on latest version.

<img width="540" alt="Screen Shot 2022-03-25 at 11 55 34 PM" src="https://user-images.githubusercontent.com/3034555/160223784-30ce06bc-460f-4a1d-9614-f4d57eea4f83.png">
s

**Comment by dnestico** [comment]
What a waste of your time sorry, I figured it out after a couple of restarts, thanks!

**Comment by deerwithacurl** [comment]
Hi! I'm gonna be honest that most likely was a Cider issue. I haven't really been active much within the Cider community for a little while now and I can most likely say that there's a chance this theme is likely very behind
